# Generated by Django 5.2.3 on 2025-07-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataFolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='img',
            field=models.ImageField(upload_to='static/projects/'),
        ),
    ]
